#This is the default Browny config. A lot of things are similar to the Towny config. But there are some things missing/renamed
#DO NOT paste your Towny config here expecting it to work. Instead, use the "/brownyadmin importtownyconfig" command from the console
#If a value isn't present, the default value will be used. If a value doesn't seem to change, please check the spelling

############################################################
# +------------------------------------------------------+ #
# |                    Browny Database                   | #
# +------------------------------------------------------+ #
############################################################

#Configures the database, this is where Browny loads all the towns, plots, nations, etc from
#Note that, unlike Towny, Browny doesn't load all data at startup (by default). Instead, it loads them when needed.
database:
    #Can be: TownyFlatfile
    #Types prefixed with Towny mean that they use a Towny compatible format.
    type: 'TownyFlatfile'
    #Controls when things are loaded into memory. Valid values are:
    #NEEDED: caches only when needed, then unloads them.
    #PERM: caches once it's needed, then keeps them in cache permanently. This is recommended.
    #ALL: caches everything once the server starts up. This is what Towny does.
    plotCaching: 'PERM'
    #controls the size of plots. It's not recommended to change this
    plotSize: 16

#controls if debug messages appear
DebugLogsEnabled: false
#Might flood the console with useless stuff and is mostly unnecessary 
SpamLogsEnabled: false 

############################################################
# +------------------------------------------------------+ #
# |                Town and Nation levels                | #
# +------------------------------------------------------+ #
############################################################

 
levels:
  # Town levels. Needs to be defined from least amount of residents to most.
  townLevels:
  - minNumResidents: 0
    nameSuffix: ' Ruins'
    mayorPrefix: 'Spirit '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 1
    upkeepModifier: 1.0
    townOutpostLimit: 0
    townBonusLimit: 16
  - minNumResidents: 1
    nameSuffix: ' (Settlement)'
    mayorPrefix: 'Hermit '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 16
    upkeepModifier: 1.0
    townOutpostLimit: 0
    townBonusLimit: 16
  - minNumResidents: 2
    nameSuffix: ' (Hamlet)'
    mayorPrefix: 'Chief '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 32
    upkeepModifier: 1.0
    townOutpostLimit: 1
    townBonusLimit: 16
  - minNumResidents: 6
    nameSuffix: ' (Village)'
    mayorPrefix: 'Baron Von '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 96
    upkeepModifier: 1.0
    townOutpostLimit: 1
    townBonusLimit: 32
  - minNumResidents: 10
    nameSuffix: ' (Town)'
    mayorPrefix: 'Viscount '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 160
    upkeepModifier: 1.0
    townOutpostLimit: 2
    townBonusLimit: 32
  - minNumResidents: 14
    nameSuffix: ' (Large Town)'
    mayorPrefix: 'Count Von '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 224
    upkeepModifier: 1.0
    townOutpostLimit: 2
    townBonusLimit: 32
  - minNumResidents: 20
    nameSuffix: ' (City)'
    mayorPrefix: 'Earl '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 320
    upkeepModifier: 1.0
    townOutpostLimit: 3
    townBonusLimit: 32
  - minNumResidents: 24
    nameSuffix: ' (Large City)'
    mayorPrefix: 'Duke '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 384
    upkeepModifier: 1.0
    townOutpostLimit: 3
    townBonusLimit: 32
  - minNumResidents: 28
    nameSuffix: ' (Metropolis)'
    mayorPrefix: 'Lord '
    namePrefix: ''
    mayorSuffix: ''
    townBlockLimit: 448
    upkeepModifier: 1.0
    townOutpostLimit: 4
    townBonusLimit: 32
  # Nation levels. -----------------------
  nation_level:
  - kingSuffix: ''
    capitalSuffix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Leader '
    capitalPrefix: ''
    minNumResidents: 0
    nationBonusOutpostLimit: 0
    nameSuffix: ' (Nation)'
    townBlockLimitBonus: 10
    namePrefix: 'Land of '
    nationZonesSize: 1
    nationTownUpkeepModifier: 1.0
  - kingSuffix: ''
    capitalSuffix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Count '
    capitalPrefix: ''
    minNumResidents: 10
    nationBonusOutpostLimit: 1
    nameSuffix: ' (Nation)'
    townBlockLimitBonus: 20
    namePrefix: 'Federation of '
    nationZonesSize: 1
    nationTownUpkeepModifier: 1.0
  - kingSuffix: ''
    capitalSuffix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Duke '
    capitalPrefix: ''
    minNumResidents: 20
    nationBonusOutpostLimit: 2
    nameSuffix: ' (Nation)'
    townBlockLimitBonus: 40
    namePrefix: 'Dominion of '
    nationZonesSize: 1
    nationTownUpkeepModifier: 1.0
  - kingSuffix: ''
    capitalSuffix: ''
    upkeepModifier: 1.0
    kingPrefix: 'King '
    capitalPrefix: ''
    minNumResidents: 30
    nationBonusOutpostLimit: 3
    nameSuffix: ' (Nation)'
    townBlockLimitBonus: 60
    namePrefix: 'Kingdom of '
    nationZonesSize: 2
    nationTownUpkeepModifier: 1.0
  - kingSuffix: ''
    capitalSuffix: ''
    upkeepModifier: 1.0
    kingPrefix: 'Emperor '
    capitalPrefix: ''
    minNumResidents: 40
    nationBonusOutpostLimit: 4
    nameSuffix: ' Empire'
    townBlockLimitBonus: 100
    namePrefix: 'The '
    nationZonesSize: 2
    nationTownUpkeepModifier: 1.0
  - kingSuffix: ''
    capitalSuffix: ''
    upkeepModifier: 1.0
    kingPrefix: 'God Emperor '
    capitalPrefix: ''
    minNumResidents: 60
    nationBonusOutpostLimit: 5
    nameSuffix: ' Realm'
    townBlockLimitBonus: 140
    namePrefix: 'The '
    nationZonesSize: 3
    nationTownUpkeepModifier: 1.0

############################################################
# +------------------------------------------------------+ #
# |                     Default Town                     | #
# +------------------------------------------------------+ #
############################################################
townDefault:
  # Default public status of the town (used for /town spawn)
  defaultPublic: true
  # Default Open status of the town (are new towns open and joinable by anyone at creation?)
  defaultOpen: false
  # Default amount of tax of a new town. This must be lower than the economy.daily_taxes.max_tax_percent setting.
  defaultTax: 0.0
  defaultPrices: #default prices and taxes of plots
    # Default town price of a plot.
    plotPrice: 0.0
    # Default amount of plot tax of a new town.
    plotTax: 0.0
    # Default town price of a embassy plot.
    commercialPlotTax: 50.0
    # Default amount of shop tax of a new town.
    commercialPlotTax: 0.0
    # Default town price of a embassy plot.
    embassyPlotPrice: 50.0
    # Default amount of embassy tax of a new town.
    embassyPlotTax: 0.0
    
    
 
############################################################
# +------------------------------------------------------+ #
# |                  Town Claim Settings                 | #
# +------------------------------------------------------+ #
############################################################
townClaim:
  # maximum number of plots any single resident can own
  maxPlotsPerResident: 100
  # maximum number used in /town claim/unclaim # commands.
  # set to 0 to disable limiting of claim radius value check.
  # keep in mind that the default value of 4 is a radius, 
  # and it will allow claiming 9x9 (80 plots) at once.
  maxClaimRadius: 4
  # Maximum number of towns allowed on the server.
  serverTownLimit: 3000

  # Minimum number of plots any towns plot must be from the next town's own plots.
  # May decrease performance if set too high. It's recommended to keep this within server render distance unless plot caching mode is set to ALL
  minTownDistance: 0
  
  # Minimum amount of plots a homeblock must be from other homeblocks
  minHomeBlockDistance: 5
  
  # Minimum number of plots an outpost must be from any other town's plots.
  minOutpostDistance: 5
 
  # Maximum distance between homeblocks.
  # This will force players to build close together.
  maxTownHomeblockDistance: 0
 
  # The maximum townblocks available to a town is (numResidents * ratio).
  # Setting this value to 0 will instead use the level based jump values determined in the town level config.
  townBlockRatio: 8
  
############################################################
# +------------------------------------------------------+ #
# |             Default new world settings               | #
# +------------------------------------------------------+ #
############################################################
# World management settings to deal with un/claiming plots
plotManagement:
    block_delete:
      enabled: 'true'
      # These items will be deleted upon a plot being unclaimed
      unclaim_delete: BED_BLOCK,TORCH,REDSTONE_WIRE,SIGN_POST,WOODEN_DOOR,WALL_SIGN,STONE_PLATE,IRON_DOOR_BLOCK,WOOD_PLATE,REDSTONE_TORCH_OFF,REDSTONE_TORCH_ON,DIODE_BLOCK_OFF,DIODE_BLOCK_ON

    mayor_plotblock_delete:
      enabled: 'true'
      # These items will be deleted upon a mayor using /plot clear
      # To disable deleting replace the current entries with NONE.
      mayor_plot_delete: WALL_SIGN,SIGN_POST
      
############################################################
# +------------------------------------------------------+ #
# |             block/item/mob protection                | #
# +------------------------------------------------------+ #
############################################################
 
protection:
 
  # Items that can be blocked within towns via town/plot flags
  # 259 - flint and steel
  # 325 - bucket
  # 326 - water bucket
  # 327 - lava bucket
  # 351 - bone/bonemeal
  # 359 - shears
  # 368 - ender pearl
  # 374 - glass bottle
  # 385 - fire charge
  itemUseIds: FLINT_AND_STEEL,BUCKET,WATER_BUCKET,LAVA_BUCKET,MINECART,STORAGE_MINECART,INK_SACK,SHEARS,ENDER_PEARL,GLASS_BOTTLE,FIREBALL,ARMOR_STAND,SKULL_ITEM,BOAT_BIRCH,BOAT_ACACIA,BOAT_DARK_OAK,BOAT_JUNGLE,BOAT,BOAT_SPRUCE,END_CRYSTAL,POWERED_MINECART,COMMAND_MINECART,EXPLOSIVE_MINECART,HOPPER_MINECART
 
  # Items which can be blocked or enabled via town/plot flags
  # 25 - noteblock
  # 54 - chest ...etc
  switchIds: DISPENSER,NOTE_BLOCK,CHEST,FURNACE,BURNING_FURNACE,WOODEN_DOOR,ACACIA_DOOR,DARK_OAK_DOOR,JUNGLE_DOOR,BIRCH_DOOR,SPRUCE_DOOR,LEVER,STONE_PLATE,IRON_DOOR_BLOCK,WOOD_PLATE,STONE_BUTTON,TRAP_DOOR,JUKEBOX,DIODE_BLOCK_OFF,DIODE_BLOCK_ON,FENCE_GATE,SPRUCE_FENCE_GATE,BIRCH_FENCE_GATE,JUNGLE_FENCE_GATE,DARK_OAK_FENCE_GATE,ACACIA_FENCE_GATE,TRAPPED_CHEST,GOLD_PLATE,IRON_PLATE,REDSTONE_COMPARATOR_OFF,REDSTONE_COMPARATOR_ON,BEACON,HOPPER,DROPPER,MINECART,STORAGE_MINECART,POWERED_MINECART,CARROT_STICK,EXPLOSIVE_MINECART,HOPPER_MINECART,WHITE_SHULKER_BOX,ORANGE_SHULKER_BOX,MAGENTA_SHULKER_BOX,LIGHT_BLUE_SHULKER_BOX,YELLOW_SHULKER_BOX,LIME_SHULKER_BOX,PINK_SHULKER_BOX,GRAY_SHULKER_BOX,SILVER_SHULKER_BOX,CYAN_SHULKER_BOX,PURPLE_SHULKER_BOX,BLUE_SHULKER_BOX,BROWN_SHULKER_BOX,GREEN_SHULKER_BOX,RED_SHULKER_BOX,BLACK_SHULKER_BOX
 
  # permitted entities https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/LivingEntity.html
  # Animals, Chicken, Cow, Creature, Creeper, Flying, Ghast, Giant, Monster, Pig, 
  # PigZombie, Sheep, Skeleton, Slime, Spider, Squid, WaterMob, Wolf, Zombie, Shulker
  # Husk, Stray, SkeletonHorse, ZombieHorse, Vex, Vindicator, Evoker, Endermite, PolarBear
 
  # Remove living entities within a town's boundaries, if the town has the mob removal flag set.
  hostileMobs: Monster,Guardian,Flying,Slime,Shulker,SkeletonHorse,ZombieHorse
 
  # Prevent the spawning of villager babies in towns.
  preventVillagerBabies: false
  # Disable creatures triggering stone pressure plates
  disableEntityStonePressurePlate: false
 
  # Controls how often Browny checks when entities should be removed
  mobRemovalSpeed: 5s
 
  # permitted entities https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/package-summary.html
  # Animals, Chicken, Cow, Creature, Creeper, Flying, Ghast, Giant, Monster, Pig, 
  # PigZombie, Sheep, Skeleton, Slime, Spider, Squid, WaterMob, Wolf, Zombie
 
  # Protect living entities within a town's boundaries from being killed by players.
  mob_types: Animals,NPC,Snowman,ArmorStand
 
  # permitted Potion Types https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionType.html
  # ABSORPTION, BLINDNESS, CONFUSION, DAMAGE_RESISTANCE, FAST_DIGGING, FIRE_RESISTANCE, HARM, HEAL, HEALTH_BOOST, HUNGER, 
  # INCREASE_DAMAGE, INVISIBILITY, JUMP, NIGHT_VISION, POISON, REGENERATION, SATURATION, SLOW , SLOW_DIGGING, 
  # SPEED, WATER_BREATHING, WEAKNESS, WITHER.
 
  # When preventing PVP prevents the use of these potions.
  potion_types: BLINDNESS,CONFUSION,HARM,HUNGER,POISON,SLOW,SLOW_DIGGING,WEAKNESS,WITHER
  
############################################################
# +------------------------------------------------------+ #
# |                 Town Notifications                   | #
# +------------------------------------------------------+ #
############################################################

# This is the format for the notifications sent as players move between plots.
# Empty a particular format for it to be ignored.

# Example:
# [notification.format]
# ~ [notification.area_[wilderness/town]][notification.splitter][notification.[no_]owner][notification.splitter][notification.plot.format]
# ... [notification.plot.format]
# ... [notification.plot.homeblock][notification.plot.splitter][notification.plot.forsale][notification.plot.splitter][notification.plot.type]
# ~ Wak Town - Lord Jebus - [Home] [For Sale: 50 Beli] [Shop]
 
notification:
  format: '&6 ~ %s'
  splitter: '&7 - '
  area_wilderness: '&2%s'
  area_wilderness_pvp: '%s'
  area_town: '&6%s'
  area_town_pvp: '%s'
  owner: '&a%s'
  no_owner: '&a%s'
  plot:
    splitter: ' '
    format: '%s'
    homeblock: '&b[Home]'
    outpostblock: '&b[Outpost]'
    forsale: '&e[For Sale: %s]'
    type: '&6[%s]'
  # If set to true MC's Title and Subtitle feature will be used when crossing into a town.
  # Could be seen as intrusive/distracting, so false by default.
  using_titles: 'false'
 
  # Requires the above using_titles to be set to true.
  # Title and Subtitle shown when entering a town or the wilderness. By default 1st line is blank, the 2nd line shows {townname} or {wilderness}.
  # You may use colour codes &f, &c and so on.
  titles:
    # Entering Town Upper Title Line
    town_title: ''
    # Entering Town Lower Subtitle line.
    town_subtitle: '&b{townname}'
    # Entering Wilderness Upper Title Line
    wilderness_title: ''
    # Entering Wilderness Lower Subtitle line.
    wilderness_subtitle: '&2{wilderness}'
  # If the notification.owner option should show name or {title} name.
  # Titles are the ones granted by nation kings.
  owner_shows_nation_title: 'false'